[[ephemeralpg]]
arch = "aarch64"
git-tree-sha1 = "e5a63f66631edc139faa4be4d0e54aed410ea8b3"
libc = "glibc"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "b042dacb6f135482ccfdbe0129c5af2cb5c37b126251f42a3e7fd6646f1d7fb8"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.1.0+0/ephemeralpg.v3.1.0.aarch64-linux-gnu.tar.gz"
[[ephemeralpg]]
arch = "aarch64"
git-tree-sha1 = "9e07ef48cf9417f44b79393895a26c6ef58de566"
libc = "musl"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "987ba6b251fe3846c1aa86da0d43fa517caf03fba3f000475e3931d1bf9be023"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.1.0+0/ephemeralpg.v3.1.0.aarch64-linux-musl.tar.gz"
[[ephemeralpg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "03027f4b9d2ae848c608e9c7b1d5e99318501e79"
libc = "glibc"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "8ded9d5b9499e33ee550aef58af734fc8269f0c0e63ec4c06d5778dab2d966c2"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.1.0+0/ephemeralpg.v3.1.0.armv7l-linux-gnueabihf.tar.gz"
[[ephemeralpg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "19ddc00814167f1b2d35f8e688838f2eafcec2cd"
libc = "musl"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "149bf603b4e7ccaec830b3523f9a68803a09ab9ddcdc6eb8aea3d2f921867b16"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.1.0+0/ephemeralpg.v3.1.0.armv7l-linux-musleabihf.tar.gz"
[[ephemeralpg]]
arch = "i686"
git-tree-sha1 = "73c6a3b10d84744dba89c954800a88cef4bd55cd"
libc = "glibc"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "7b7524ba61b5ee70462c14816d85bf5ba3bc4fb7691212115589264d8041302d"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.1.0+0/ephemeralpg.v3.1.0.i686-linux-gnu.tar.gz"
[[ephemeralpg]]
arch = "i686"
git-tree-sha1 = "9a36da6babeddf30ed52479f57ec0b4eb4cd0a2a"
libc = "musl"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "eaa05e53facf7a3aa8780aa27ecf3f24b5c7afc62880265f06ae1ead12fa6a96"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.1.0+0/ephemeralpg.v3.1.0.i686-linux-musl.tar.gz"
[[ephemeralpg]]
arch = "powerpc64le"
git-tree-sha1 = "d40d1cf18b2734089ba022b8daca452a6cbed87b"
libc = "glibc"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "6d9e056beae8cf5404b6bbbbaae9a2d46a05aa8784fd116af5247ef988f76315"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.1.0+0/ephemeralpg.v3.1.0.powerpc64le-linux-gnu.tar.gz"
[[ephemeralpg]]
arch = "x86_64"
git-tree-sha1 = "5e800539c252162a9c3e78f2b7364ee2ba37aca8"
os = "macos"

    [[ephemeralpg.download]]
    sha256 = "f46fa50b661e31bdf4b7511481156f90bafa46ed0dd711b5fb793b51d34b0dbd"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.1.0+0/ephemeralpg.v3.1.0.x86_64-apple-darwin.tar.gz"
[[ephemeralpg]]
arch = "x86_64"
git-tree-sha1 = "d9824ae880e758f00d95e60e8760d368a536ed79"
libc = "glibc"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "f30c27aa3ab49e744167ae069a3e9e5765409880cf6c2f447921fa95082a918f"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.1.0+0/ephemeralpg.v3.1.0.x86_64-linux-gnu.tar.gz"
[[ephemeralpg]]
arch = "x86_64"
git-tree-sha1 = "f164c085e36d500fbb73c7bb3ebf1d82a1024729"
libc = "musl"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "f9b0e80b7023aa6aef8023bd344db534d3ab9c233fe449e94ab060c8d6674e41"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.1.0+0/ephemeralpg.v3.1.0.x86_64-linux-musl.tar.gz"
[[ephemeralpg]]
arch = "x86_64"
git-tree-sha1 = "6a10229e034e4f80e1a452bdc9022cc49c841c5e"
os = "freebsd"

    [[ephemeralpg.download]]
    sha256 = "84977d18d03526c8df74ae15d8dbde00a83303bc5a63023b3639f23257920483"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.1.0+0/ephemeralpg.v3.1.0.x86_64-unknown-freebsd.tar.gz"
