[[ephemeralpg]]
arch = "aarch64"
git-tree-sha1 = "50d6de31ce508bf4d283fd372cea3f33f9266f47"
libc = "glibc"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "2b436feeb5a32df7e93351aff9e59c0e68703f6da516acdef511cdd19522a067"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.0.0+0/ephemeralpg.v3.0.0.aarch64-linux-gnu.tar.gz"
[[ephemeralpg]]
arch = "aarch64"
git-tree-sha1 = "e8681e12e4caf3e779a6eea16d2f9b60f1c491ac"
libc = "musl"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "e42c878d3c65cbdae6aa85e3958c66712069ff8ba59cf7f2eae7065ac76e6d1c"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.0.0+0/ephemeralpg.v3.0.0.aarch64-linux-musl.tar.gz"
[[ephemeralpg]]
arch = "armv7l"
git-tree-sha1 = "ebb1d706ce9c6184c72df500cf465f77c188b498"
libc = "glibc"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "69aae8e306783ecec2176144813e66b56f5d98ff7f9af5c6de22a8d850263abb"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.0.0+0/ephemeralpg.v3.0.0.armv7l-linux-gnueabihf.tar.gz"
[[ephemeralpg]]
arch = "armv7l"
git-tree-sha1 = "96aed9a30dd751a8040da66bbc2a6388106d7a12"
libc = "musl"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "2dc6b025c6626d5fb949c0cf94ea2d4b654eec2618f1a715ad716a4610fb6728"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.0.0+0/ephemeralpg.v3.0.0.armv7l-linux-musleabihf.tar.gz"
[[ephemeralpg]]
arch = "i686"
git-tree-sha1 = "773002e092cde0fef92eba05f8bb2ac0ba683b89"
libc = "glibc"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "05be014ac8f9dc18270fe6a98b6b56f1ee6aed161287b0934fedc48738e645e4"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.0.0+0/ephemeralpg.v3.0.0.i686-linux-gnu.tar.gz"
[[ephemeralpg]]
arch = "i686"
git-tree-sha1 = "8dc148896bd233912b35b25c4fd1a7115373c768"
libc = "musl"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "8f32783d24610f48dc9f6872d4f71b358e8fd0468fc2006ba6a5afc74facb040"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.0.0+0/ephemeralpg.v3.0.0.i686-linux-musl.tar.gz"
[[ephemeralpg]]
arch = "powerpc64le"
git-tree-sha1 = "4244fd11726ca7229a022803e499b85053992126"
libc = "glibc"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "e1d728d1d30de65207736ce2bead53617649f25161d8ed4752117c488cd61f74"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.0.0+0/ephemeralpg.v3.0.0.powerpc64le-linux-gnu.tar.gz"
[[ephemeralpg]]
arch = "x86_64"
git-tree-sha1 = "fb59aca30be24112c6e5f86b3fa4a27eb737864a"
os = "macos"

    [[ephemeralpg.download]]
    sha256 = "563223ded0fd1b591caea29966a5acfdc06f5cec836fbd933fdf11d8188cbbd8"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.0.0+0/ephemeralpg.v3.0.0.x86_64-apple-darwin14.tar.gz"
[[ephemeralpg]]
arch = "x86_64"
git-tree-sha1 = "74ed41f4ec6e73bc2d901bdf6911557b2c2f7c15"
libc = "glibc"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "7fcc53450b749c5c6c5727ed28a8f8fd601db60c04239a4e24b737b4a1e6e188"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.0.0+0/ephemeralpg.v3.0.0.x86_64-linux-gnu.tar.gz"
[[ephemeralpg]]
arch = "x86_64"
git-tree-sha1 = "22750ab2878e9d38bce711df6eb6bc752b6cc68c"
libc = "musl"
os = "linux"

    [[ephemeralpg.download]]
    sha256 = "b2c2e485ed904e974fa8774aa2b65b01349673c205dd9dc9158138914438749c"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.0.0+0/ephemeralpg.v3.0.0.x86_64-linux-musl.tar.gz"
[[ephemeralpg]]
arch = "x86_64"
git-tree-sha1 = "74c98a685691436705db31e2944bb61364516db6"
os = "freebsd"

    [[ephemeralpg.download]]
    sha256 = "e13fc1adec324cbb08953dda7563d1571a10c5f90a5eb059b665b17183f6e83e"
    url = "https://github.com/JuliaBinaryWrappers/ephemeralpg_jll.jl/releases/download/ephemeralpg-v3.0.0+0/ephemeralpg.v3.0.0.x86_64-unknown-freebsd11.1.tar.gz"
