# Autogenerated wrapper script for ephemeralpg_jll for x86_64-linux-gnu
export ddl_compare, getsocket, pg_tmp

JLLWrappers.@generate_wrapper_header("ephemeralpg")
JLLWrappers.@declare_executable_product(ddl_compare)
JLLWrappers.@declare_executable_product(getsocket)
JLLWrappers.@declare_executable_product(pg_tmp)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        ddl_compare,
        "bin/ddl_compare",
    )

    JLLWrappers.@init_executable_product(
        getsocket,
        "bin/getsocket",
    )

    JLLWrappers.@init_executable_product(
        pg_tmp,
        "bin/pg_tmp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
